src/interior/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from interior_app.views import (PortfolioObjectList, 
                                ArticlesList, 
                                ArticleDetail)

urlpatterns = [
    url(r'^$', 'interior_app.views.home', name='home'),
    url(r'^subscribe/$', 'interior_app.views.subscribe', name='subscribe'),
    url(r'^portfolio/$', PortfolioObjectList.as_view(), name='portfolio'),
    url(r'^portfolio/bysort/$', 'interior_app.views.select_by_sort', name='select_by_sort'),
    url(r'^portfolio/(?P<object_id>\d+)/$', 'interior_app.views.portfolio_detail', name='portfolio_detail'),
    url(r'^services/$', 'interior_app.views.services', name='services'),
    url(r'^contacts/$', 'interior_app.views.contacts', name='contacts'),
    url(r'^blog/$', ArticlesList.as_view(), name='blog'),
    url(r'^blog/(?P<pk>\d+)/$', ArticleDetail.as_view(), name='article_detail'),
    url(r'^search/$', 'interior_app.views.search', name='search'),
    url(r'^category/(?P<id>\d+)/$', 'interior_app.views.category', name='category'),
    url(r'^tag/(?P<id>\d+)/$', 'interior_app.views.tag', name='tag'),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/interior_app/models.py
# coding: utf-8
from __future__ import unicode_literals
from django.db import models


class Sort(models.Model):
    name = models.CharField(max_length=50, null=True, blank=True, verbose_name="Тип объекта:")

    def __unicode__(self):
        return self.name

class PortfolioObject(models.Model):
    sort = models.ForeignKey(Sort, null=True)
    address = models.CharField(max_length=50, null=True, blank=True)
    area = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    draft = models.ImageField(upload_to='drafts', null=True, blank=True)
           
    def __unicode__(self):
        return self.address

class Photo(models.Model):
    portfolio = models.ForeignKey(PortfolioObject, null=True, blank=True)
    photo = models.ImageField(upload_to='photos', null=True, blank=True)

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __unicode__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __unicode__(self):
        return self.name

class Article(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField()
    pub_date = models.DateField()
    category = models.ForeignKey(Category)
    tag = models.ManyToManyField(Tag)
    
    class Meta:
        ordering = ['-pub_date']
           
    def __unicode__(self):
        return self.title

    def onephoto(self):
        onephoto = self.articlephoto_set.all()[0]
        return onephoto

class ArticlePhoto(models.Model):
    article = models.ForeignKey(Article, null=True, blank=True)
    article_photo = models.ImageField(upload_to='article_photo', null=True, blank=True)

class Subscriber(models.Model):
    email = models.EmailField('', max_length=100, null=True, blank=True)
    
    def __unicode__(self):
        return self.email

class Feedback(models.Model):
    text = models.TextField(null=True, blank=True)
    name = models.CharField(max_length=50, null=True, blank=True)
    photo = models.ImageField(upload_to='photos', null=True, blank=True)

src/templates/article_detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
<title>Дизайн интерьера стили статьи советы</title>
{% endblock %}

{% block article_detail %}

<div class="container article_page">

	<h2>{{ article.title }}</h2>

	<div class="row">
		
		<div class="col-md-4">
		{% for item in article.articlephoto_set.all %}
			<img src="{{ item.article_photo.url }}" class='img-responsive img-thumbnail' />
		{% endfor %}
		</div>

		<div class='col-md-8'>
			<p>{{ article.text }}</p>
		</div>

	</div>

</div>

{% endblock article_detail %}

src/templates/articles_by_category.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
<title>Дизайн интерьера стили статьи советы</title>
{% endblock %}

{% block blog %}

<div class="container articles_by_category">
	<h1>Статьи в категории - {{ category.name }}</h1>
	{% for article in articles %}
	
		<h3><a href="/blog/{{ article.id }}">{{ article.title }}</a></h3>
		
	{% endfor %}
</div>

{% endblock blog %}

src/templates/articles_by_tag.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
<title>Дизайн интерьера стили статьи советы</title>
{% endblock %}

{% block blog %}

<div class="container articles_by_tag">

	<h1>Статьи по тэгу - {{ tag.name }}</h1>
	{% for article in articles %}
	
		<h3><a href="/blog/{{ article.id }}">{{ article.title }}</a></h3>
		
	{% endfor %}

</div>

{% endblock blog %}

src/templates/blog.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
<title>Дизайн интерьера стили статьи советы</title>
{% endblock %}

{% block blog %}

		<section class="blog" id="blog">
			<div class="container">
				
				<div class="row">
					<div class="col-md-12">
						<div class="section-title st-center" id='articles'>
							<p>Статьи и полезные советы</p>
						</div>
					</div>
				</div>
				
				<div class="block">
					
					<div class="col-md-8">
						<div class="blog-post">
						{% for article in articles %}
							<h2 class="post-title"><a href="{% url 'article_detail' article.id %}">{{ article.title }}</a></h2>
							
							{% if article.articlephoto_set.all %}						
							<div class="post-thumb">
								<a href="{% url 'article_detail' article.id %}"><img src="{{ article.onephoto.article_photo.url }}" alt="" class="img-responsive"></a>
							</div>
							{% else %}
							
							{% endif %}
							
							<div class="post-content">
								<p>{{ article.text|truncatewords:50 }}<a href="{% url 'article_detail' article.id %}" class="more-link">Читать дальше <span class="meta-nav">&rarr;</span></a></p>
							</div>
							
							<div class="post-meta">
								<p><strong>{{ article.pub_date }}</strong></p>
							</div>
						{% endfor %}
						</div>
					</div>
					
					<div class="col-md-4">
						<div class="widgets">
							
							<div class="widget">
								<form action="/search/" method="GET">{% csrf_token %}
									<div class="input-group">
										<input type="text" id="search_input" class="form-control" name="search_input"placeholder="Поиск...">
										<span class="input-group-btn">
											<button id="search_btn" class="btn btn-default btn-lg" type="submit"><i class="fa fa-search"></i></button>
										</span>
									</div>
								</form>
							</div>
							
							<div class="widget">
								<h2 class="widget-title">Стили интерьера</h2>
								<ul>
								{% for category in categories %}
									<li><a href="/category/{{ category.id }}">{{ category }} <span class="badge pull-right">{{ category.article_set.count }}</span></a></li>
								{% endfor %}
								</ul>
							</div>

							<div id="tag_cloud-3" class="widget widget_tag_cloud">
								<h2 class="widget-title">Тэги</h2>
								<div class="tagcloud">
								{% for tag in tags %}
									<a href="/tag/{{ tag.id }}">{{ tag }}</a>
								{% endfor %}
								</div>
							</div>
						
						</div>
					</div>
				
				</div>
  				
  				<div class='row'>
  					<div class="pagination">
 
				    {% if articles.has_previous %}
				        <a class='lg' href="?page={{ articles.previous_page_number }}">←</a>
				    {% endif %}
				 
				    {% for num in articles.paginator.page_range %}
				        {% if num == articles.number %}
				            <span class="current lg"><b>{{ num }}</b></span>
				        {% else %}
				            <a class='lg' href="?page={{ num }}"> {{ num }}</a>
				        {% endif %} 
				    {% endfor %}
				 
				    {% if articles.has_next %}
				        <a class='lg' href="?page={{ articles.next_page_number }}">→</a>
				    {% endif %}

				    </div>
 				</div>
			
			</div>
		</section>

{% endblock blog %}

src/templates/contacts.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block contacts %}

		<section class="contact" id="contact">
			<div class="container">
                <div id="phone-numbers" class="row">
					<div class="col-md-6 col-md-offset-3">
						<div class="row">
							<div class="col-md-2">
								<i class="fa fa-mobile fa-5x"></i>
							</div>
							<div class="col-md-10">
								<h4>+7 903 618 15 65</h4>
								<h4>+7 966 159 92 97</h4>
								<h4>+38 068 533 9271</h4>
							</div>
						</div>
					</div>
				</div>

				<div id="emails" class="row">
					<div class="col-md-6 col-md-offset-3">
						<div class="row">
							<div class="col-md-2">
								<i class="fa fa-envelope fa-5x"></i>
							</div>
							<div class="col-md-10">
								<h4>imat.site@gmail.com</h4>
								<h4>imat-art@mail.ru</h4>
							</div>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col-md-6 col-md-offset-3">
						<h3>Или напишите нам прямо сейчас:</h3>
					</div>
				</div>

				<div class='row'>
				<div class="col-md-6 col-md-offset-3">
					<form action="" method="POST">{% csrf_token %}

						{{ form|crispy }}

						<button class="btn btn-main btn-lg" type="submit" id="send" data-loading-text="<i class='fa fa-spinner fa-spin'></i> Sending...">Отправить</button>

					</form>
				</div>
				</div>

				<div id="adres" class="row">
					<div class="col-md-6 col-md-offset-3">
						<div class="row">
							<div class="col-md-2">
								<i class="fa fa-university fa-3x"></i>
							</div>
							<div class="col-md-10">
								<address><h4>Москва</h4></address>
							</div>
						</div>
					</div>
				</div>

			</div>
		</section>

{% endblock contacts %}

src/templates/contacts_thanks.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block contacts %}

<div id='thanks' class="col-md-8 col-md-offset-2">
	<h1>Спасибо, что обратились к нам.</h1>
	<h1>Мы ответим Вам в ближайшее время.</h1>
</div>

{% endblock contacts %}

src/templates/footer.html
{% load staticfiles %}

<footer class="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">

						<p>&copy; Design-creatiff {% now "Y" %} </p>

					</div>
				</div>
			</div>
</footer>

src/templates/js.html
{% load staticfiles %}

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="{% static 'js/jquery.min.js' %}"></script>

        <!-- jQuery Light gallery -->
        <script src="{% static 'js/lightgallery/picturefill.min.js' %}"></script>
        <script src="{% static 'js/lightgallery/lightgallery.min.js' %}"></script>
        <script src="{% static 'js/lightgallery/lg-thumbnail.js' %}"></script>
        <script src="{% static 'js/lightgallery/lg-fullscreen.js' %}"></script>
        <script src="{% static 'js/lightgallery/lg-autoplay.js' %}"></script>
        <script src="{% static 'js/lightgallery/lg-zoom.js' %}"></script>

        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/jquery.easing.min.js' %}"></script>
        <script src="{% static 'js/jquery.appear.js' %}"></script>
        <script src="{% static 'js/jquery.nicescroll.min.js' %}"></script>
        <script src="{% static 'js/jquery.countTo.js' %}"></script>
        <script src="{% static 'js/jquery.shuffle.modernizr.js' %}"></script>
        <script src="{% static 'js/jquery.shuffle.js' %}"></script>
        <script src="{% static 'js/owl.carousel.js' %}"></script>
        <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
        <script src="{% static 'js/revslider.js' %}"></script>
		<script src="{% static 'js/script.js' %}"></script>

		<script type="text/javascript">
        jQuery(document).ready(function(){
            jQuery('#unicorn-rev-slider').show().revolution({
                dottedOverlay: 'none',
                delay: 5000,
                startwidth: 0,
                startheight:500,

                hideThumbs: 200,
                thumbWidth: 200,
                thumbHeight: 50,
                thumbAmount: 2,

                navigationType: 'thumb',
                navigationArrows: 'solo',
                navigationStyle: 'round',

                touchenabled: 'on',
                onHoverStop: 'on',

                swipe_velocity: 0.7,
                swipe_min_touches: 1,
                swipe_max_touches: 1,
                drag_block_vertical: false,

                spinner: 'spinner0',
                keyboardNavigation: 'off',

                navigationHAlign: 'center',
                navigationVAlign: 'bottom',
                navigationHOffset: 0,
                navigationVOffset: 20,

                soloArrowLeftHalign: 'left',
                soloArrowLeftValign: 'center',
                soloArrowLeftHOffset: 20,
                soloArrowLeftVOffset: 0,

                soloArrowRightHalign: 'right',
                soloArrowRightValign: 'center',
                soloArrowRightHOffset: 20,
                soloArrowRightVOffset: 0,

                shadow: 0,
                fullWidth: 'on',
                fullScreen: 'on',

                stopLoop: 'off',
                stopAfterLoops: -1,
                stopAtSlide: -1,

                shuffle: 'off',

                autoHeight: 'on',
                forceFullWidth: 'off',
                fullScreenAlignForce: 'off',
                minFullScreenHeight: 0,
                hideNavDelayOnMobile: 1500,

                hideThumbsOnMobile: 'off',
                hideBulletsOnMobile: 'off',
                hideArrowsOnMobile: 'off',
                hideThumbsUnderResolution: 0,

                hideSliderAtLimit: 0,
                hideCaptionAtLimit: 0,
                hideAllCaptionAtLilmit: 0,
                startWithSlide: 0,
                fullScreenOffsetContainer: ''
            });

            var link = window.location.pathname;
            $('ul.nav li a[href="' + link + '"]').parent().addClass('active');

            if ( $(document).height() <= $(window).height() ) {
                $("footer.site-footer").addClass("navbar-fixed-bottom");
            }

        });
        </script>

src/templates/navbar.html
{% load staticfiles %}

		<header class="st-navbar">
			<nav class="navbar navbar-default navbar-fixed-top clearfix" >
				<div class="container"><!-- Brand and toggle get grouped for better mobile display -->
					<div class="navbar-header">
						<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sept-main-nav">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'images/logo.png' %}" alt="" class="img-responsive"></a>
					</div>

					<!-- Collect the nav links, forms, and other content for toggling -->
					<div class="collapse navbar-collapse main-nav" id="sept-main-nav">
						<ul class="nav navbar-nav navbar-right">
							<li><a href="{% url 'home' %}">Главная</a></li>
							<li><a href="{% url 'portfolio' %}">Портфолио</a></li>
							<li><a href="{% url 'services' %}">Услуги</a></li>
							<li><a href="{% url 'blog' %}">Статьи</a></li>
							<li><a href="{% url 'contacts' %}">Контакты</a></li>
						</ul>
					</div><!-- /.navbar-collapse -->
				</div>
			</nav>
		</header>

src/templates/portfolio_detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block portfolio_detail %}

<div class="container portfolio_page">
	<div class="row">
		<div class='col-md-12'>
			<h2>{{ item.address }}</h2>
			<p>{{ item.tip }}</p>
			<p>{{ item.area }} кв. м</p>
			<img src="{{ item.draft.url }}" class='img-responsive img-thumbnail' />
		</div>
	</div>

	<div class="row" id="lightgallery" >
		{% for item in item.photo_set.all %}
		<div class='col-md-4 col-sm-6 item' data-src="{{ item.photo.url }}" >
			<img src="{{ item.photo.url }}" class='img-responsive img-thumbnail' />
		</div>
		{% endfor %}
	</div>
</div>

{% endblock portfolio_detail %}

src/templates/search_result.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
<title>Дизайн интерьера стили статьи советы</title>
{% endblock %}

{% block blog %}

<div class="container search_result">

{% if articles.count > 0 %}

<h1>Список статей подходящих под Ваш запрос:</h1>

{% for article in articles %}

<h3><a href="/blog/{{ article.id }}">{{ article.title }}</a></h3>

{% endfor %}

{% else %}

<h1>Соответствий не найдено.</h1>
<h1>Попробуйте другие варианты.</h1>

{% endif %}

</div>

{% endblock blog %}

src/templates/selected_by_sort.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block portfolio %}

<div class="container portfolio_page">
	
	<div class="row">
		<div class="col-md-12">
			<h1>Объекты типа {{ name }}</h1>
		</div>		
	</div>

	<div class="row">
		<div class="col-md-4">
			<form action="{% url 'select_by_sort' %}" method="POST"> {% csrf_token %}
						
				{{ form|crispy }}

				<button class="btn btn-main btn-lg" type="submit" id="select_by_sort">Выбрать</button>

			</form>
		</div>		
	</div>	

	<div class="row">
		<div class='col-md-12'>
			<div class="row">
			{% for portfolio in portfolios %}
				{% for item in portfolio.photo_set.all %}
				<div class='col-md-4 col-sm-6'>
					<a href='{% url "portfolio_detail" portfolio.id %}'><img src="{{ item.photo.url }}" class='img-responsive img-thumbnail' /></a>
				</div>
				{% endfor %}
			{% endfor %}
			</div>
		</div>
	</div>

</div>

{% endblock portfolio %}

src/templates/services.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block services %}

<section class="services" id="services">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="section-title st-center">
          <p>Услуги</p>
        </div>
        <div>
          <ol>
            <li>Предпроектный анализ и планировочное решение
              <ol>
                <li>Выезд на объект</li>
                <li>Выполнение обмерного чертежа с указанием инженерных коммуникаций</li>
                <li>Разработка нескольких вариантов планировочных решений</li>
              </ol>
            </li>
            <li>Разработка концепции и эскизный проект (коллаж, фотографии,предварительное колористическое решение интерьера) подбор отделочных материалов, мебели и оборудования.</li>
            <li>Архитектурно - дизайнерское проектирование ( РАБОЧИЙ ПРОЕКТ)
              <ol>
                <li>Обмерный чертеж с привязкой инженерных коммуникаций</li>
                <li>План демонтажа перегородок и инженерных коммуникаций</li>
                <li>План возводимых перегородок с маркировкой оконных и дверных проемов</li>
                <li>План размещения оборудования</li>
                <li>План размещения санитарно - технического оборудования с привязкой выпусков и приложением монтажных чертежей.</li>
                <li>Спецификация и смета сантехнического оборудования</li>
                <li>План потолков и с указанием типа используемого материала, отдельных узлов и сечений. ( Количество чертежей зависит от уровня сложности потолочных конструкций)</li>
                <li>План полов с указанием отметки уровня пола, рисунка и размеров. (Экспликация напольных покрытий с указанием площади)</li>
                <li>План размещения электрического пола с привязкой регулятора</li>
                <li>План размещения радиаторов</li>
                <li>План размещения осветительных приборов с привязками</li>
                <li>Разрезы и развертки стен, с раскладкой плитки и декоративными элементами</li>
                <li>Схема размещения кондиционеров</li>
                <li>План размещения розеток и выключателей</li>
                <li>3D Визуализация</li>
              </ol>
            </li>
            <li>Авторский надзор за строительством и декорированием интерьера ( Кол-во выездов на объект по согласованию с заказчиком а так же строительной бригадой)
            </li>
          </ol>
        </div>
      </div>
    </div>
  </div>
</section>
<div class="row">
  <div class="col-md-8">
  </div>
</div>
{% endblock services %}